config/routes.rb
Sarang::Application.routes.draw do

  get "sites/show"

  

  devise_for :users
  resources :users, :only => [:index, :show] do
     resources :subdomains, :shallow => true
 end
 resources :users, :only => [:index, :show] do
     resources :propers
 end
 resources :propers
 match '/' => 'sites#show', :constraints => { :subdomain => /.+/ }

	  root :to => "home#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/proper.rb
class Proper < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :photo
end

app/models/site.rb
class Site < Subdomain
end

app/models/subdomain.rb
class Subdomain < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :name, :case_sensitive => false
  validates_presence_of :name

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :subdomains, :dependent => :destroy
	has_many :propers, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  validates_uniqueness_of :company_name, :email, :case_sensitive => false
  attr_accessible :company_name, :contact_person, :contact_no, :sales_team_contact, :agent_type, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	  def index
	  	@search = Proper.search(params[:search])
    	@propers = @search.all
    	
      	respond_to do |format|
      		format.html # index.html.erb
      		format.json { render json: @propers }
      	end
      end
end

app/controllers/propers_controller.rb
class PropersController < ApplicationController
	
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :find_user, :except => [:index, :show]
  # GET /propers
  # GET /propers.json
  def index
  	@search = Proper.search(params[:search])
    @propers = @search.all # or @search.relation to lazy load in view

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @propers }
      format.xml { render :xml => @propers }
    end
  end
  
  # GET /propers/1
  # GET /propers/1.json
  def show
    @proper = Proper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proper }
#      format.xml  { render :action => "population.xml.builder", :layout => false }
    
      format.xml { render :action => "hcubestrip.xml.builder" }
    end
  end
  
  # GET /propers/new
  # GET /propers/new.json
  def new
    @proper = Proper.new(:user => @user)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proper }
    end
  end

  # GET /propers/1/edit
  def edit
  	@check = Proper.find(params[:id])
  	if @check.email == current_user.email
       @proper = Proper.find(params[:id])
    else
    	flash[:notice] = "not allowed"
    	redirect_to propers_url
    end
  end

  # POST /propers
  # POST /propers.json
  def create
    @proper = Proper.new(params[:proper])

    respond_to do |format|
      if @proper.save
        format.html { redirect_to @proper, notice: 'Proper was successfully created.' }
        format.json { render json: @proper, status: :created, location: @proper }
      else
        format.html { render action: "new" }
        format.json { render json: @proper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /propers/1
  # PUT /propers/1.json
  def update
    @proper = Proper.find(params[:id])

    respond_to do |format|
      if @proper.update_attributes(params[:proper])
        format.html { redirect_to @proper, notice: 'Property was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @proper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /propers/1
  # DELETE /propers/1.json
  def destroy
  	@check = Proper.find(params[:id])
  	if @check.email == current_user.email
    	@proper = Proper.find(params[:id])
    	@proper.destroy
    	
    	respond_to do |format|
      		format.html { redirect_to @user }
      		format.json { head :ok }
    	end
    else
    	flash[:alert] = "not allowed"
    	redirect_to propers_url
    end
  end
  
  protected

    def find_user
      if params[:user_id]
       @user = User.find(params[:user_id])
      else
        @proper = Proper.find(params[:id])
        @user = @proper.user
        
      end
      unless current_user == @user
        redirect_to @user, :alert => "Are you logged in properly? You are not allowed to create or change someone else's subdomain."
      end
    end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def show
  	@site = Site.find_by_name!(request.subdomain)
  end

end

app/controllers/subdomains_controller.rb
class SubdomainsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_user, :except => [:index, :show]
  respond_to :html

  def index
    @subdomains = Subdomain.all
    respond_with(@subdomains)
  end

  def show
    @subdomain = Subdomain.find(params[:id])
    respond_with(@subdomain)
  end

  def new
  @subdomain = Subdomain.new(:user => @user)
  respond_with(@subdomain)
  end

  def create
    @subdomain = Subdomain.new(params[:subdomain])
    if @subdomain.save
      flash[:notice] = "Successfully created subdomain."
    end
    redirect_to @user
  end

  def edit
    @subdomain = Subdomain.find(params[:id])
    respond_with(@subdomain)
  end

  def update
    @subdomain = Subdomain.find(params[:id])
    if @subdomain.update_attributes(params[:subdomain])
      flash[:notice] = "Successfully updated subdomain."
    end
    respond_with(@subdomain)
  end

  def destroy
    @subdomain = Subdomain.find(params[:id])
    @subdomain.destroy
    flash[:notice] = "Successfully destroyed subdomain."
    redirect_to @user
  end

  protected

    def find_user
      if params[:user_id]
        @user = User.find(params[:user_id])
      else
        @subdomain = Subdomain.find(params[:id])
        @user = @subdomain.user
      end
      unless current_user == @user
        redirect_to @user, :alert => "Are you logged in properly? You are not allowed to create or change someone else's subdomain."
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/propers_helper.rb
module PropersHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/subdomains_helper.rb
module SubdomainsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sarang</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "swfobject.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="outerWrapper">
		<div id="header">
  			<div id="headerNav">
    			<ul class="level-0" id="cssmw3">
    			<li><a href="#">Contact Us</a></li>
            	<li><a href="#">Leasing</a></li>
            	<li><%= link_to "Renting", propers_path %></li>
    			<li><a href="properties.html">Selling</a></li>
  				<li><%= link_to "Buying", propers_path %></li>
  				<li><%= link_to "Home", root_url %></li>
				</ul>
  			</div>
    			<a href="#"><div id="logo"><%= image_tag('Untitled.png', :size => '300x129') %></div></a>
    
  		</div>
  		<div id="userNav">
  			<div id="log">
<% if user_signed_in? %>
		<div id="user_profile">
			<ul class="level-0" id="cssmw3">
				<li><%= link_to "Profile", current_user %></li>
				
			</ul>
		</div>
			Signed in as <%= current_user.email %>. Not you?
			<%= link_to "Sign Out", destroy_user_session_path %>
		<% else %>
			Not Logged In. 
			<%= link_to "Sign Up", new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %>
		<% end %>
		</div>
		</div>
		
		<div id="contentWrapper">
			<%= yield %>
		</div>
      </div>
</body>
</html>

app/views/layouts/plain.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sarang</title>
  <%= stylesheet_link_tag    "plain" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "swfobject.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="outerWrapper">
		<div id="header">
  			<div id="headerNav">
    			<ul class="level-0" id="cssmw3">
    			<li><a href="#">Contact Us</a></li>
            	<li><a href="#">Leasing</a></li>
            	<li><%= link_to "Renting" %></li>
    			<li><a href="properties.html">Selling</a></li>
  				<li><%= link_to "Buying", propers_path %></li>
  				<li><%= link_to "Home", root_url %></li>
				</ul>
  			</div>
    			<a href="#"><div id="logo"><%= image_tag('Untitled.png', :size => '300x129') %></div></a>
    
  		</div>
  		<div id="userNav">
  			<div id="log">
<% if user_signed_in? %>
		<div id="user_profile">
			<ul class="level-0" id="cssmw3">
				<li><%= link_to "Profile", current_user %></li>
				
			</ul>
		</div>
			Signed in as <%= current_user.email %>. Not you?
			<%= link_to "Sign Out", destroy_user_session_path %>
		<% else %>
			Not Logged In. 
			<%= link_to "Sign Up", new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %>
		<% end %>
		</div>
		</div>
		
		<div id="contentWrapper">
			<%= yield %>
		</div>
      </div>
</body>
</html>

app/views/propers/edit.html.erb
<div style="padding-left: 20px;">
	<br />
<h1>Editing proper</h1>
<br />
</div>

  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>
  
    	<div id="fInfo">
		<div class="leftpr">
<%= render 'form' %>

<%= link_to 'Show', @proper %> |
<%= link_to 'Back', propers_path %>
		</div>
	</div>
	
  <div class="clr"></div>
  <div id="footer">
  	<div style="float: left; padding-left: 20px;">
  		<P>&nbsp;</p><P>&nbsp;</p>
    &copy; 2011 Saranghomes
    <a href="<%= root_url %>" style="border-left: 1px solid #000;">Home</a>
    <a href="#" style="border-left: 1px solid #000;">About Us</a>
    <a href="#" style="border-left: 1px solid #000;">Contact Us</a>
    </div>
    <div style="float:right; padding-right: 20px;">
    	<a href="http://www.1by0creations.com">Created by : <%= image_tag('1by0_creations_logo.png', :size => '50x65', :title => '1 by 0 Creations') %></a>
    </div>
  </div>

app/views/propers/index.html.erb
<div style="padding-left: 20px;">
	<br />
<h1>Listing Properties</h1>
<br />
</div>
<%= @propers %>
<div id="fInfo">
		<div class="searchpr">
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>
  <h3 style="background:#000; font-family: Trajan Pro; font-size: 18px;">FIND YOUR PROPERTY</h3>
  <%= form_for @search do |f| %>
  	<table>
  		<tr>
  			<td>
  				<%= f.label :property_type_contains, "Property Type :" %>
  				<%= f.select :property_type_contains, [ '1 BHK', '2 BHK', '3 BHK' ], :include_blank => true %>
  				<br /><br />
		    </td>
		    <td>
  				<%= f.label :cost_gteq, "Price Range :" %>
  				<br />
  				<%= f.text_field :cost_gteq, :size => 8, :style => "background: #323232; border: 1px solid #000; color:#FFF;" %>
  				<%= f.label :cost_lteq, "to" %>
  				<%= f.text_field :cost_lteq, :size => 8, :style => "background: #323232; border: 1px solid #000; color:#FFF;" %>
  				<br /><br />
  			</td>
  			<td align="center">
  				<%= f.label :area_contains, "Area :" %>
  				<%= f.select( :area_contains, Proper.all.collect {|s| [ s.area, s.area ]}, :include_blank => true ) %>
  				<br /><br />
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<%= f.label :amneties_contains, "Amneties :" %>
  				<%= f.text_field :amneties_contains, :size => 28, :style => "background: #323232; border: 1px solid #000; color:#FFF;" %>
  				<br /><br />
  			</td>
  			<td></td>
  			<td>
  				<%= f.label :utilities_contains, "Utilities In Proximity :" %>
  				<%= f.text_field :utilities_contains, :size => 28, :style => "background: #323232; border: 1px solid #000; color:#FFF;" %>
  				<br /><br />
  			</td>
  		</tr>
  		<tr>
  			<td>
  				<%= f.label :property_for_contains, "Interested In :" %>
  				<%= f.radio_button( :property_for_contains, 'Sale' ) %> Buy
   				<%= f.radio_button( :property_for_contains, 'Rent' ) %> Rent
  				<br /><br />
  			</td>
  			<td></td>
  			<td></td>
  		</tr>
  		<tr>
  			<td>
    			<%= f.submit "SEARCH FOR MY DREAM HOUSE" %>
    			<br /><br />
    		</td>
    		<td></td>
    		<td></td>
    	</tr>
    	</table>
  <% end %>

		</div>
	</div>
	
<% @propers.each do |proper| %>
	<div id="fInfo">
		<div class="leftpr">
			<div class="proptitle">
				<%= proper.property_type %>, Sector <%= proper.sector %> in <%= proper.area %>
			</div>

	<table width="100%" cellpadding="5">
  <tr style="border-bottom: 1px solid #222;">
    <td width="230">Picture</td>
    <td width="200" style="font-family: Verdana; font-size: 14px; color: #817339; font-weight: bold;"  class="colm">Total Price : Rs. <%= proper.cost %></td>
    <td width="180px;" style="font-family: Verdana; font-size: 14px; font-weight: bold; color: #0AD; " class="colm">Description</td>
    <td style="font-family: Verdana; font-size: 14px; font-weight: bold; color: #0AD"  class="colm">Property For</td>
    <td></td>
  </tr>
  <tr style="font-family: Verdana; font-size: 12px; color: #000;">
    <td><%= image_tag proper.photo.url, :size => "230x100" %></td>
    <td valign="top" style="font-family: Verdana; font-size: 12px; color: #000;"  class="colm">Area : <%= proper.area_sqft %> sq-ft</td>
    <td class="colm"><%= proper.description %></td>
    <td  class="colm"><%= proper.property_for %></td>
    <td style="color: #FFF;">
    	<%= link_to 'Show Details', proper %><br />
    	<% if user_signed_in? %>
    	<%if proper.email == current_user.email %>
    	<%= link_to 'Edit', edit_proper_path(proper) %><br />
    	<%= link_to 'Delete', proper, confirm: 'Are you sure?', method: :delete %>
    	<% end %>
    	<% end %>
    
</td>
  </tr>

</table>

<br />
		</div>
	</div>
<% end %>
  <div class="clr"></div>
  <div id="footer">
  	<div style="float: left; padding-left: 20px;">
  		<P>&nbsp;</p><P>&nbsp;</p>
    &copy; 2011 Saranghomes
    <a href="<%= root_url %>" style="border-left: 1px solid #000;">Home</a>
    <a href="#" style="border-left: 1px solid #000;">About Us</a>
    <a href="#" style="border-left: 1px solid #000;">Contact Us</a>
    </div>
    <div style="float:right; padding-right: 20px;">
    	<a href="http://www.1by0creations.com">Created by : <%= image_tag('1by0_creations_logo.png', :size => '50x65', :title => '1 by 0 Creations') %></a>
    </div>
  </div>

app/views/propers/new.html.erb
<div style="padding-left: 20px;">
	<br />
<h1>New property</h1>
<br />
</div>

  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>
  	<div id="fInfo">
		<div class="leftpr">

<%= render 'form' %>


<%= link_to 'Back', propers_path %>
		</div>
	</div>
<div class="clr"></div>
  <div id="footer">
  	<div style="float: left; padding-left: 20px;">
  		<P>&nbsp;</p><P>&nbsp;</p>
    &copy; 2011 Saranghomes
    <a href="<%= root_url %>" style="border-left: 1px solid #000;">Home</a>
    <a href="#" style="border-left: 1px solid #000;">About Us</a>
    <a href="#" style="border-left: 1px solid #000;">Contact Us</a>
    </div>
    <div style="float:right; padding-right: 20px;">
    	<a href="http://www.1by0creations.com">Created by : <%= image_tag('1by0_creations_logo.png', :size => '50x65', :title => '1 by 0 Creations') %></a>
    </div>
  </div>

app/views/propers/show.html.erb
<p id="notice"><%= notice %></p>
	<div id="fInfo">
		<div class="leftpr">

<p>
	<div id="krpanoH" style="width:100%; align: center;">
		
	</div>
</p>
<br />
<p>
  <b>Address:</b>
  <%= @proper.flat_no %>, <%= @proper.building_name %>, Plot <%= @proper.plot %>, <br />
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sector <%= @proper.sector %>, <%= @proper.area %>. - <%= @proper.pincode %>.<br />
</p>
<br />
<p>
  <b>Description:</b>
  <%= @proper.description %>
</p>
<br />
<p>
  <b>Area sqft:</b>
  <%= @proper.area_sqft %>
</p>
<br />
<p>
  <b>Cost:</b>
  <%= @proper.cost %>
</p>
<br />
<p>
  <b>Property type:</b>
  <%= @proper.property_type %>
</p>
<br />
<p>
  <b>Property for:</b>
  <%= @proper.property_for %>
</p>
<br />
<p>
  <b>Utilities:</b>
  <%= @proper.utilities %>
</p>
<br />
<p>
  <b>Amneties:</b>
  <%= @proper.amneties %>
</p>
<br />
<br />
<br />
<%= link_to 'Edit', edit_proper_path(@proper) %> |
<%= link_to 'Back', propers_path %>
		</div>
	</div>

<script type="text/javascript">
// <![CDATA[
	if (typeof(deconcept) !== 'undefined' && deconcept.SWFObjectUtil.getPlayerVersion().major >= 6)
	{
		var so = new SWFObject("../../assets/krpano.swf", "krpanoSWFObject1", "575", "275", "9.0.28","#000000");
		so.addParam("allowFullScreen","true");
		so.addVariable("pano", "<%= @proper.id %>.xml");
		so.useExpressInstall('../../assets/swfobject/expressinstall.swf');
		so.setAttribute('xiRedirectUrl', window.location);
		if ( so.write("krpanoH") ) { var mousewheelfixes = new SWFkrpanoMouseWheel(so); }
	}
	else
	{
		document.getElementById("krpanoH").innerHTML = '<table width="100%" height="100%"><tr valign="middle"><td><center>ERROR:<br><br>Adobe Flash Player 9 needed<br><br><br><a href="http://www.adobe.com/go/getflashplayer/"  target="_blank"><IMG SRC="http://www.macromedia.com/images/shared/download_buttons/get_flash_player.gif" BORDER="1"></a><br>...click here to download...<br><br><br><br></center></td></tr></table>';
	}
// ]]>
</script>

  <div class="clr"></div>
  <div id="footer">
  	<div style="float: left; padding-left: 20px;">
  		<P>&nbsp;</p><P>&nbsp;</p>
    &copy; 2011 Saranghomes
    <a href="<%= root_url %>" style="border-left: 1px solid #000;">Home</a>
    <a href="#" style="border-left: 1px solid #000;">About Us</a>
    <a href="#" style="border-left: 1px solid #000;">Contact Us</a>
    </div>
    <div style="float:right; padding-right: 20px;">
    	<a href="http://www.1by0creations.com">Created by : <%= image_tag('1by0_creations_logo.png', :size => '50x65', :title => '1 by 0 Creations') %></a>
    </div>
  </div>

app/views/sites/show.html.erb
<div style="padding-left: 20px;">
	<br />
<h1><%= @site.name %></h1>
<br />
</div>
	<div id="fInfo">
		<div class="leftpr">
<p>Belongs to: <%= link_to @site.user.company_name, user_url(@site.user) %></p>
		</div>
	</div>
<div class="clr"></div>
  <div id="footer">
  	<div style="float: left; padding-left: 20px;">
  		<P>&nbsp;</p><P>&nbsp;</p>
    &copy; 2011 Saranghomes
    <a href="<%= root_url %>" style="border-left: 1px solid #000;">Home</a>
    <a href="#" style="border-left: 1px solid #000;">About Us</a>
    <a href="#" style="border-left: 1px solid #000;">Contact Us</a>
    </div>
    <div style="float:right; padding-right: 20px;">
    	<a href="http://www.1by0creations.com">Created by : <%= image_tag('1by0_creations_logo.png', :size => '50x65', :title => '1 by 0 Creations') %></a>
    </div>
  </div>

app/views/subdomains/_form.html.erb
<% if @subdomain.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@subdomain.errors.count, "error") %> prohibited this subdomain from being saved:</h2>
    <ul>
    <% @subdomain.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= fields_for @subdomain do |f| %> 
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.hidden_field(:user_id, :value => @subdomain.user_id) %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subdomains/index.html.erb
<div style="padding-left: 20px;">
	<br />
<h1>Subdomains</h1>
<br />
</div>

	<div id="fInfo">
		<div class="leftpr">
<table>
<% @subdomains.each do |subdomain| %>
  <tr>
    <td><%= link_to subdomain.name, subdomain %></td>
    <td>(belongs to <%= link_to subdomain.user.company_name, user_url(subdomain.user) %>)</td>
    <td><%= link_to 'Edit', edit_subdomain_path(subdomain) %></td>
    <td><%= link_to 'Destroy', subdomain, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

		</div>
	</div>
	<div class="clr"></div>
  <div id="footer">
  	<div style="float: left; padding-left: 20px;">
  		<P>&nbsp;</p><P>&nbsp;</p>
    &copy; 2011 Saranghomes
    <a href="<%= root_url %>" style="border-left: 1px solid #000;">Home</a>
    <a href="#" style="border-left: 1px solid #000;">About Us</a>
    <a href="#" style="border-left: 1px solid #000;">Contact Us</a>
    </div>
    <div style="float:right; padding-right: 20px;">
    	<a href="http://www.1by0creations.com">Created by : <%= image_tag('1by0_creations_logo.png', :size => '50x65', :title => '1 by 0 Creations') %></a>
    </div>
  </div>

app/views/subdomains/show.html.erb
<div style="padding-left: 20px;">
	<br />
<h1><%= @subdomain.name %></h1>
<br />
</div>

	<div id="fInfo">
		<div class="leftpr">
<p>Belongs to: <%= link_to @subdomain.user.company_name, user_url(@subdomain.user) %></p>
<%= link_to 'Edit', edit_subdomain_path(@subdomain) %>
		</div>
	</div>
	<div class="clr"></div>
  <div id="footer">
  	<div style="float: left; padding-left: 20px;">
  		<P>&nbsp;</p><P>&nbsp;</p>
    &copy; 2011 Saranghomes
    <a href="<%= root_url %>" style="border-left: 1px solid #000;">Home</a>
    <a href="#" style="border-left: 1px solid #000;">About Us</a>
    <a href="#" style="border-left: 1px solid #000;">Contact Us</a>
    </div>
    <div style="float:right; padding-right: 20px;">
    	<a href="http://www.1by0creations.com">Created by : <%= image_tag('1by0_creations_logo.png', :size => '50x65', :title => '1 by 0 Creations') %></a>
    </div>
  </div>

app/views/users/show.html.erb
<div style="padding-left: 20px;">
	<br />
<h1><%= @user.company_name %></h1>
<br />
</div>

	<div id="fInfo">
		<div class="leftpr">
<p><%= @user.email %></p>
<br />
<p><%= link_to 'Edit', edit_user_registration_path %></p>
<p><%= link_to 'List of Users', users_path %></p>
<br />
<h3 style="color: #000; font-weight:bold;"><%= @user.company_name %>'s Subdomain</h3>
<table>
<% @user.subdomains.each do |subdomain| %>
  <tr>
    <td><%= link_to subdomain.name, subdomain %></td>
    <td><%= link_to 'Edit', edit_subdomain_path(subdomain) %></td>
    <td><%= link_to 'Delete', subdomain, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>

</table>

<br /><br /><br />

<h3 style="color: #000; font-weight:bold;"><%= @user.company_name %>'s Properties</h3>
<table width="100%" border="0" cell-padding="0">
<% @user.propers.each do |proper| %>
	<tr class="proptitle">
    <td><%= proper.property_type %>, Sector <%= proper.sector %>, <%= proper.area %> for <%= proper.property_for %></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
  	<td width="400"><%= image_tag proper.photo.url, :size => "600x200" %></td>
    <td><%= link_to 'Show', proper %></td>
    <td><%= link_to 'Edit', edit_proper_path(proper) %></td>
    <td><%= link_to 'Delete', proper, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
  <tr height="20px;">
  	<td></td>
  	<td></td>
  	<td></td>
  	<td></td>
  </tr>
  <% end %>
  </table>
<br />
<% if @user.subdomains.count < 1 %>
<%= link_to "Add New Subdomain", new_user_subdomain_path(@user) %>
<% end %>
<%= link_to "Add Property", new_user_proper_path(@user) %>
		</div>
	</div>
<div class="clr"></div>
  <div id="footer">
  	<div style="float: left; padding-left: 20px;">
  		<P>&nbsp;</p><P>&nbsp;</p>
    &copy; 2011 Saranghomes
    <a href="<%= root_url %>" style="border-left: 1px solid #000;">Home</a>
    <a href="#" style="border-left: 1px solid #000;">About Us</a>
    <a href="#" style="border-left: 1px solid #000;">Contact Us</a>
    </div>
    <div style="float:right; padding-right: 20px;">
    	<a href="http://www.1by0creations.com">Created by : <%= image_tag('1by0_creations_logo.png', :size => '50x65', :title => '1 by 0 Creations') %></a>
    </div>
  </div>